<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3ee0c458661fb77c1cfa265b7a97ecc7
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3ee0c458661fb77c1cfa265b7a97ecc7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3ee0c458661fb77c1cfa265b7a97ecc7::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
